spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall3?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&enabledTLSProtocols=TLSv1.2&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      connection-timeout: 20000
  redis:
    host: localhost
    database: 10
    lettuce:
      pool:
        min-idle: 4
        max-active: 20
        max-idle: 10

mall3:
  auth:
    redis:
      host: localhost
      port: 6379
      database: 11